// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhiozairbkcntfyvqykd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoaW96YWlyYmtjbnRmeXZxeWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjU3MzgsImV4cCI6MjA2Mzg0MTczOH0.F4CaKnVnMkJYE6HncnzjnGMFE9lV5GBzWcpUs0gSLPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);